name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  release:
    if: github.event_name == 'release'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build project for release
        run: cargo build --release

      - name: Rename binary based on platform
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            mv ./target/release/reson ./target/release/reson_linux64
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv ./target/release/reson ./target/release/reson_darwin
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            powershell -Command "Rename-Item -Path ./target/release/reson.exe -NewName reson_win64.exe"
          fi
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ matrix.os == 'ubuntu-latest' && './target/release/reson_linux64' || '' }}
            ${{ matrix.os == 'windows-latest' && './target/release/reson_win64.exe' || '' }}
            ${{ matrix.os == 'macos-latest' && './target/release/reson_darwin' || '' }}
