name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  release:
    if: github.event_name == 'release'

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build project for release
        run: cargo build --release

      - name: Debug release context
        run: |
          echo "Release Upload URL: ${{ github.event.release.upload_url }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "OS: ${{ matrix.os }}"

      - name: Upload Release Asset (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/reson
          name: reson_linux64

      - name: Upload Release Asset (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/reson.exe
          name: reson_win64.exe

      - name: Upload Release Asset (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/reson
          name: reson_darwin